# Build Step
FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

# Production Step
FROM node:22-alpine

WORKDIR /app

# Copy only files needed
COPY --from=builder /app/.output ./.output
COPY --from=builder /app/package*.json ./

RUN npm ci --only=production --omit=dev --ignore-scripts

CMD ["node", ".output/server/index.mjs"]
