# Build Step
FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci --production

COPY . .

# Production Step
FROM node:24-alpine AS runner

WORKDIR /app

COPY --from=builder /app /app

CMD ["node", "index.js"]
